/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficas;

import EDD.AVLTree;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Iterator;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import static proyecto2_edd.Proyecto2_EDD.arbolAVL;
import sun.audio.AudioPlayer;

/**
 *
 * @author tracs
 */
public class Arbol_Avl extends javax.swing.JFrame {

    /**
     * Creates new form Arbol_Avl
     */
    public String nom;
    public String ape;
           
    public Arbol_Avl(String n,String a) {
        arbolAVL = new AVLTree();
        nom = n;
        ape = a;
        initComponents();
        setLayout(null);
        setTitle("Arbol Avl - "+n+" "+a);
        jScrollPane1.setPreferredSize(new Dimension(800, 460));
        setLocationRelativeTo(null);
    }

    private Arbol_Avl() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setText("Arbol AVL");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cargar Arbol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Automatico");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Manual");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jLabel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4)
                        .addGap(48, 48, 48)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton2)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario(nom, ape);
        usuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public String ruta = "";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:    
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        File Archivo = jfc.getSelectedFile();
        ruta = Archivo.getAbsolutePath();
        
    }//GEN-LAST:event_jButton2ActionPerformed
    Timer timer = null;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        timer = null;
        final JSONParser parser = new JSONParser();
        if((timer==null)&&(!"".equals(ruta))){
            timer = new Timer(1000, new ActionListener() {
                
                @Override
                public void actionPerformed(ActionEvent ae) {
                    Object obj = null;
                    try {
                        obj = parser.parse(new FileReader(ruta));
                    } catch (IOException ex) {
                        Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ParseException ex) {
                        Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JSONObject arbol=(JSONObject) obj;
                    JSONArray jsonA =(JSONArray)arbol.get("Input");
                    //System.out.println(jsonA.size());
                    JSONObject usuario;
                    //System.out.println(jsonA.get(0));
                    int num;
                    int c =1;
                    for(Object j: jsonA){
                        
                        usuario = (JSONObject) j;
                        System.out.println(usuario.get("num"));
                        num = (int)(long)usuario.get("num");
                        arbolAVL.insertar(num);
                        try {
                            Thread.sleep(3000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        ImageIcon icono = new ImageIcon("C:\\Users\\tracs\\Desktop\\limpio.jpg"); // esta llamada espera a que la imagen esté cargada.
                        int a  = icono.getIconHeight();
                        int b = icono.getIconWidth();
                        System.out.println(a+" "+b);
                        jLabel2.setSize(a, b);
                        jLabel2.setIcon(icono);
                        jLabel2.validate();
                        jLabel2.revalidate();
                        if(c>=3){
                            arbolAVL.graficarArbol("1",0);
                            System.out.println("graficar -----");
                        }
                        try {
                            Thread.sleep(3000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        icono = new ImageIcon("C:\\Users\\tracs\\Desktop\\ArbolAVL.jpg"); // esta llamada espera a que la imagen esté cargada.
                        a  = icono.getIconHeight();
                        b = icono.getIconWidth();
                        System.out.println(a+" "+b);
                        jLabel2.setSize(a, b);
                        jLabel2.setIcon(icono);
                        jLabel2.validate();
                        jLabel2.revalidate();
                        jLabel2.repaint();
                        
                        System.out.println(c);
                        c++;
                        
                    }
                    timer.stop();
                }
            });
            timer.start();
            
        }else{
            JOptionPane.showMessageDialog(null, "NO A INGRESADO ARCHIVO");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public int cc = 0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:-
        timer.stop();
        cc = 0;
        String ss = jTextField1.getText();
        System.out.println(jTextField1.getText().getClass());
        int num = Integer.parseInt(ss.trim());
        arbolAVL.graficarArbol("2", num);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
        } 
        ImageIcon icono = new ImageIcon("C:\\Users\\tracs\\Desktop\\ArbolAVL2.jpg");
         
        jLabel2.setIcon(icono);
        cc=2;
        System.out.println("eliminacion");
        arbolAVL.eliminar(num);
        arbolAVL.graficarArbol("1", 0);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("eliminacion completa");
        icono = new ImageIcon("C:\\Users\\tracs\\Desktop\\ArbolAVL.jpg");
        jLabel2.setIcon(icono);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
        }
        arbolAVL.graficarArbol("1", 0);
        System.out.println("final");
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        timer = null;
        final JSONParser parser = new JSONParser();
        if((timer==null)&&(!"".equals(ruta))){
            timer = new Timer(1000, new ActionListener() {
                
                @Override
                public void actionPerformed(ActionEvent ae) {
                    Object obj = null;
                    try {
                        obj = parser.parse(new FileReader(ruta));
                    } catch (IOException ex) {
                        Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ParseException ex) {
                        Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JSONObject arbol=(JSONObject) obj;
                    JSONArray jsonA =(JSONArray)arbol.get("Input");
                    //System.out.println(jsonA.size());
                    JSONObject usuario;
                    //System.out.println(jsonA.get(0));
                    int num;
                    int c =0;
                    for(Object j: jsonA){
                        
                        usuario = (JSONObject) j;
                        System.out.println(usuario.get("num"));
                        num = (int)(long)usuario.get("num");
                        arbolAVL.insertar(num);
                        try {
                            Thread.sleep(4000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        ImageIcon icono = new ImageIcon("C:\\Users\\tracs\\Desktop\\limpio.jpg"); // esta llamada espera a que la imagen esté cargada.
                        int a  = icono.getIconHeight();
                        int b = icono.getIconWidth();
                        System.out.println(a+" "+b);
                        jLabel2.setSize(a, b);
                        jLabel2.setIcon(icono);
                        jLabel2.validate();
                        jLabel2.revalidate();
                        if(c>=3){
                            arbolAVL.graficarArbol("1",0);
                            System.out.println("graficar -----");
                        }
                        try {
                            Thread.sleep(4000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Arbol_Avl.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        icono = new ImageIcon("C:\\Users\\tracs\\Desktop\\ArbolAVL.jpg"); // esta llamada espera a que la imagen esté cargada.
                        a  = icono.getIconHeight();
                        b = icono.getIconWidth();
                        System.out.println(a+" "+b);
                        jLabel2.setSize(a, b);
                        jLabel2.setIcon(icono);
                        jLabel2.validate();
                        jLabel2.revalidate();
                        jLabel2.repaint();
                        System.out.println(c);
                        c++;
                        
                    }
                    timer.stop();
                }
            });
            timer.start();
            
        }else{
            JOptionPane.showMessageDialog(null, "NO A INGRESADO ARCHIVO");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arbol_Avl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arbol_Avl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arbol_Avl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arbol_Avl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arbol_Avl().setVisible(true);
            }
        });
    }
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
